spring.application.name=devops-app
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.show-details=always
management.endpoint.health.probes.enabled=true
management.metrics.export.prometheus.enabled=true
info.app.name=DevOps App
info.app.version=2.0.0
info.app.course=EFEFIC-FDVP20261
